CREATE TABLE event (
    id LONGTEXT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    img_url VARCHAR(100) NOT NULL,
    event_url LONGTEXT NOT NULL,
    date TIMESTAMP NOT NULL,
    remote BOOLEAN NOT NULL
);